export const firebaseConfigKeys = {
  NX_FIREBASE_API_KEY: "NX_FIREBASE_API_KEY",
  NX_FIREBASE_API_MESSAGING_SENDER_ID: "NX_FIREBASE_API_MESSAGING_SENDER_ID",
  NX_FIREBASE_API_STORAGE_BUCKET: "NX_FIREBASE_API_STORAGE_BUCKET",
  NX_FIREBASE_APP_ID: "NX_FIREBASE_APP_ID",
  NX_FIREBASE_AUTH_DOMAIN: "NX_FIREBASE_AUTH_DOMAIN",
  NX_FIREBASE_PROJECT_ID: "NX_FIREBASE_PROJECT_ID",
}